//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.13 at 03:01:06 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://test.com/soaptest", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.test.soaptest;
